### ISSUE TITLE
Возможность описания правил в `importRules` через glob

### ISSUE THREAD

**Issue by k-egor-smirnov** [VKCOM/elephize#70]
Хочется уметь игнорировать целые папки и модули, в которых 100% неподдерживаемый код для транспиляции. Не проверял, возможно ли это сейчас, но было бы круто в этих glob поддержать алисы. Например, 
`
"importRules": {
  "#helpers": { "ignore": true }
}
`

**Comment by ctizen** [comment]
Сделал глобы. Формат правда будет в терминах файловой системы, а не в терминах алиасов webpack/typescript, но думаю что это не такая большая беда.
